// <auto-generated />
using System;
using DataAccessLayer.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(BankDbContext))]
    [Migration("20260715154932_AddedConstraintForDeposit")]
    partial class AddedConstraintForDeposit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Entities.Bank", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("BIC")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)")
                        .IsFixedLength();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BIC" }, "UQ_banks_BIC")
                        .IsUnique();

                    b.HasIndex(new[] { "Address" }, "UQ_banks_address")
                        .IsUnique();

                    b.HasIndex(new[] { "Title" }, "UQ_banks_title")
                        .IsUnique();

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "г. Минск, ул. Сурганова, 43",
                            BIC = "ALFABY2X",
                            Title = "Альфа-Банк"
                        },
                        new
                        {
                            Id = 2L,
                            Address = "г. Минск, ул. В.Хоружей 31А",
                            BIC = "PJCBBY2X",
                            Title = "Приорбанк"
                        },
                        new
                        {
                            Id = 3L,
                            Address = "г. Минск, пр-к Дзержинского, 18",
                            BIC = "AKBBBY2X",
                            Title = "Беларусбанк"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.BankAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasMaxLength(28)
                        .HasColumnType("nchar(28)")
                        .IsFixedLength();

                    b.Property<long>("BankId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("ClosedAt")
                        .HasColumnType("date");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<decimal>("MoneyBalance")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateOnly>("OpenedAt")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("ClientId");

                    b.HasIndex(new[] { "BankAccountNumber" }, "UQ_bank_account_bank_account_number")
                        .IsUnique();

                    b.ToTable("BankAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BankAccountNumber = "0000000000000000000000000000",
                            BankId = 1L,
                            Currency = "BYN",
                            MoneyBalance = 999999999999m,
                            OpenedAt = new DateOnly(2026, 7, 15),
                            Status = "Active",
                            Type = "Current"
                        },
                        new
                        {
                            Id = 2L,
                            BankAccountNumber = "1111111111111111111111111111",
                            BankId = 2L,
                            Currency = "BYN",
                            MoneyBalance = 999999999999m,
                            OpenedAt = new DateOnly(2026, 7, 15),
                            Status = "Active",
                            Type = "Current"
                        },
                        new
                        {
                            Id = 3L,
                            BankAccountNumber = "2222222222222222222222222222",
                            BankId = 3L,
                            Currency = "BYN",
                            MoneyBalance = 999999999999m,
                            OpenedAt = new DateOnly(2026, 7, 15),
                            Status = "Active",
                            Type = "Current"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long?>("PassportId")
                        .HasColumnType("bigint");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nchar(13)")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("PassportId")
                        .IsUnique()
                        .HasFilter("[PassportId] IS NOT NULL");

                    b.HasIndex(new[] { "PhoneNumber" }, "UQ_clients_phone_number")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Credit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BankAccountId")
                        .HasColumnType("bigint");

                    b.Property<long>("BankId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("ClosedAt")
                        .HasColumnType("date");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("LoanBalance")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("LoanInterest")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("LoanTerm")
                        .HasColumnType("int");

                    b.Property<DateOnly>("OpenedAt")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId")
                        .IsUnique()
                        .HasFilter("[BankAccountId] IS NOT NULL");

                    b.HasIndex("BankId");

                    b.HasIndex("ClientId");

                    b.ToTable("Credits", t =>
                        {
                            t.HasCheckConstraint("CK_Credit_LoanInterest", "LoanInterest >= 14 AND LoanInterest <= 25");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Deposit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BankAccountId")
                        .HasColumnType("bigint");

                    b.Property<long>("BankId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("ClosedAt")
                        .HasColumnType("date");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("DepositAmount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<float>("DepositInterest")
                        .HasColumnType("real");

                    b.Property<int>("DepositTerm")
                        .HasColumnType("int");

                    b.Property<DateOnly>("OpenedAt")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId")
                        .IsUnique()
                        .HasFilter("[BankAccountId] IS NOT NULL");

                    b.HasIndex("BankId");

                    b.HasIndex("ClientId");

                    b.ToTable("Deposits", t =>
                        {
                            t.HasCheckConstraint("CK_Deposit_DepositInterest", "DepositInterest > 5 AND DepositInterest <= 11");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BankId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long?>("PassportId")
                        .HasColumnType("bigint");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PersonellNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nchar(13)")
                        .IsFixedLength();

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("PassportId")
                        .IsUnique()
                        .HasFilter("[PassportId] IS NOT NULL");

                    b.HasIndex(new[] { "PersonellNumber" }, "UQ_employee_personell_number")
                        .IsUnique();

                    b.HasIndex(new[] { "PhoneNumber" }, "UQ_employee_phone_number")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Log", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("NewValue")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("TargetRowId")
                        .HasColumnType("int");

                    b.Property<string>("TargetTable")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TypeOperation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Passport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nchar(14)")
                        .IsFixedLength();

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nchar(7)")
                        .IsFixedLength();

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdentificationNumber" }, "UQ_passport_identification_number")
                        .IsUnique();

                    b.HasIndex(new[] { "Number" }, "UQ_passport_number")
                        .IsUnique();

                    b.ToTable("Passports");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<long>("ReceiverId")
                        .HasColumnType("bigint");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("TransactionAmount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.BankAccount", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Bank", "Bank")
                        .WithMany("BankAccounts")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.Client", "Client")
                        .WithMany("BankAccounts")
                        .HasForeignKey("ClientId");

                    b.Navigation("Bank");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Client", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Passport", "Passport")
                        .WithOne("Client")
                        .HasForeignKey("DataAccessLayer.Entities.Client", "PassportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Passport");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Credit", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.BankAccount", "BankAccount")
                        .WithOne("Credit")
                        .HasForeignKey("DataAccessLayer.Entities.Credit", "BankAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccessLayer.Entities.Bank", "Bank")
                        .WithMany("Credits")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.Client", "Client")
                        .WithMany("Credits")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("BankAccount");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Deposit", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.BankAccount", "BankAccount")
                        .WithOne("Deposit")
                        .HasForeignKey("DataAccessLayer.Entities.Deposit", "BankAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccessLayer.Entities.Bank", "Bank")
                        .WithMany("Deposits")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.Client", "Client")
                        .WithMany("Deposits")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("BankAccount");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Employee", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Bank", "Bank")
                        .WithMany("Employees")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.Passport", "Passport")
                        .WithOne("Employee")
                        .HasForeignKey("DataAccessLayer.Entities.Employee", "PassportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bank");

                    b.Navigation("Passport");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Log", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Employee", "Employee")
                        .WithMany("Logs")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Transaction", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.BankAccount", "Receiver")
                        .WithMany("TransactionReceivers")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.BankAccount", "Sender")
                        .WithMany("TransactionSenders")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Bank", b =>
                {
                    b.Navigation("BankAccounts");

                    b.Navigation("Credits");

                    b.Navigation("Deposits");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.BankAccount", b =>
                {
                    b.Navigation("Credit");

                    b.Navigation("Deposit");

                    b.Navigation("TransactionReceivers");

                    b.Navigation("TransactionSenders");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Client", b =>
                {
                    b.Navigation("BankAccounts");

                    b.Navigation("Credits");

                    b.Navigation("Deposits");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Employee", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Passport", b =>
                {
                    b.Navigation("Client")
                        .IsRequired();

                    b.Navigation("Employee")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
